# config.yaml
checkers:
  - code: BECE
    name: "BECE Checker"
    price: 23
  - code: WASSCE
    name: "WASSCE Checker"
    price: 25
  - code: NOVDEC
    name: "Nov/Dec Checker"
    price: 25
  - code: NSS
    name: "NSS Checker"
    price: 30

forms:
  university:
    - code: UG
      name: "University of Ghana"
      price: 299
    - code: KNUST
      name: "KNUST"
      price: 299
    # … add up to 10 universities
  college:
    default_price: 399
  nursing:
    default_price: 299

telegram:
  token_env_var: TELEGRAM_TOKEN

paystack:
  secret_key_env_var: PAYSTACK_SECRET
